spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: houseware
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8087
  servlet:
    context-path: /houseware-service





