spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: houseware
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: doangiadung2020@gmail.com
    password: mondev2020
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
server:
  port: 8087
  servlet:
    context-path: /houseware-service






