spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: houseware
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 25MB
server:
  port: 8087
  servlet:
    context-path: /houseware-service






